version: '3'
services:
  joomla:
    image: joomla
    container_name: joomla
    ports:
      - 8080:80
    environment:
      - JOOMLA_DB_HOST=mariadb
      - JOOMLA_DB_USER=db_username
      - JOOMLA_DB_PASSWORD=db_password
      - JOOMLA_DB_NAME=db_name
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=db_username
      - MYSQL_PASSWORD=db_password
    restart: always
